name: CI

on: [ push ]

env:
  BuildConfiguration: 'Release'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Test
      run: dotnet test --no-restore --configuration $BuildConfiguration

    - name: Build
      run: dotnet build --no-restore --configuration $BuildConfiguration

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        path: '**/*.nupkg'
