name: CI

on: [ push ]

env:
  Major: 3
  Minor: 0
  Patch: 0
  BuildConfiguration: 'Release'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        clean: true

    - name: Set Version
      if: ${{ github.ref == 'refs/heads/master' }}
      run: |
        echo "version=$Major.$Minor.$Patch" >> $GITHUB_ENV
        echo "assembly_version=$Major.$Minor.$Patch.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

    - name: Set Version
      if: ${{ github.ref != 'refs/heads/master' }}
      run: |
        echo "version=$Major.$Minor.$Patch-preview2" >> $GITHUB_ENV
        echo "assembly_version=$Major.$Minor.$Patch.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: |
        dotnet build --configuration $BuildConfiguration --no-restore -p:Version=${{ env.version }} -p:AssemblyVersion=${{ env.assembly_version }}

    - name: Test
      env:
        CoinbaseApiKey__Key: ${{ secrets.COINBASEAPIKEY__KEY }}
        CoinbaseApiKey__Passphrase: ${{ secrets.COINBASEAPIKEY__PASSPHRASE }}
        CoinbaseApiKey__Secret: ${{ secrets.COINBASEAPIKEY__SECRET }}
      run: |
        dotnet test --configuration $BuildConfiguration --no-build --collect:"XPlat Code Coverage" --logger:"console;verbosity=detailed" --settings ${{github.workspace}}/test/coverletArgs.runsettings

    - name: Report test coverage reports to Codecov
      shell: bash
      run: |
        bash <(curl -s https://codecov.io/bash)

    - name: Pack
      run: |
        dotnet pack --configuration $BuildConfiguration --no-restore -p:Version=${{ env.version }} -p:AssemblyVersion=${{ env.assembly_version }}

    - name: NuGet push nuget.org
      if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' }}
      run: |
        dotnet nuget push $GITHUB_WORKSPACE/src/LDZ.Coinbase.Api/bin/$BuildConfiguration/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate --source https://api.nuget.org/v3/index.json

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: coinbase-api.${{ env.assembly_version }}
        path: '**/*.nupkg'
